using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace hhnl.CascadingCompute.Generators.Generators;

[Generator]
public sealed class CascadingComputeInterceptorGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "hhnl.CascadingCompute.Shared.Attributes.CascadingComputeAttribute";
    private static readonly SymbolDisplayFormat NullableFullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var invocations = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (ctx, _) => GetCandidate(ctx))
            .Where(static candidate => candidate is not null)!
            .Select(static (candidate, _) => candidate!);

        context.RegisterSourceOutput(invocations.Collect(), static (spc, candidates) => Execute(spc, candidates));
    }

    private static InvocationCandidate? GetCandidate(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
            return null;

        var methodSymbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
        if (methodSymbol is null)
            return null;

        if (!HasCascadingComputeAttribute(methodSymbol))
            return null;

        if (!IsSupportedMethod(methodSymbol))
            return null;

        var location = GetMethodNameLocation(invocation);
        if (location is null || !location.IsInSource)
            return null;

        var filePath = location.SourceTree?.FilePath;
        if (filePath is null || string.IsNullOrWhiteSpace(filePath) || IsGeneratedFile(filePath))
            return null;

        var mappedLineSpan = location.GetMappedLineSpan();
        var sourcePath = string.IsNullOrWhiteSpace(mappedLineSpan.Path) ? filePath : mappedLineSpan.Path;
        var sourceLineNumber = mappedLineSpan.StartLinePosition.Line + 1;

#pragma warning disable RSEXPERIMENTAL002
        var interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation);
#pragma warning restore RSEXPERIMENTAL002
        if (interceptableLocation is null)
            return null;

        return new InvocationCandidate(methodSymbol, interceptableLocation, sourcePath, sourceLineNumber);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<InvocationCandidate> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    sealed file class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        sb.AppendLine("        {");
        sb.AppendLine("            _ = version;");
        sb.AppendLine("            _ = data;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace hhnl.CascadingCompute.Interceptors");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class CascadingComputeInterceptors");
        sb.AppendLine("    {");

        var index = 0;
        foreach (var candidate in candidates)
        {
            var methodSymbol = candidate.Method;
            var methodDefinition = methodSymbol.OriginalDefinition;
            if (methodSymbol.ContainingType is null)
                continue;

            var location = candidate.Location;

            var receiverType = methodSymbol.ContainingType.ToDisplayString(NullableFullyQualifiedFormat);
            var returnType = methodSymbol.ReturnType.ToDisplayString(NullableFullyQualifiedFormat);
            var cascadingComputeAccessor = methodSymbol.ContainingType.TypeKind == TypeKind.Class
                ? $"(({receiverType}.CascadingComputeWrapper)__instance.CascadingCompute)"
                : "__instance.CascadingCompute";
            var methodName = methodDefinition.Name;
            var methodTypeParameters = GetInterceptorTypeParameters(methodSymbol);
            var methodConstraints = GetInterceptorTypeConstraints(methodSymbol);
            var methodTypeArguments = GetMethodTypeArguments(methodDefinition);
            var parameters = GetParameterList(methodSymbol);
            var arguments = string.Join(", ", methodSymbol.Parameters.Select(parameter => EscapeIdentifier(parameter.Name)));
            var interceptorName = GetInterceptorName(methodName, index++);

            sb.AppendLine($"        // Source: {NormalizeCommentText(candidate.SourcePath)}:{candidate.SourceLineNumber}");
            sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute({location.Version}, {SymbolDisplay.FormatLiteral(location.Data, true)})]");
            sb.Append("        public static ");
            sb.Append(returnType);
            sb.Append(' ');
            sb.Append(interceptorName);
            sb.Append(methodTypeParameters);
            sb.Append("(this ");
            sb.Append(receiverType);
            sb.Append(" __instance");
            if (!string.IsNullOrEmpty(parameters))
            {
                sb.Append(", ");
                sb.Append(parameters);
            }
            sb.AppendLine(")");
            foreach (var constraint in methodConstraints)
            {
                sb.Append("        ");
                sb.AppendLine(constraint);
            }
            sb.AppendLine("        {");
            sb.Append("            return ");
            sb.Append(cascadingComputeAccessor);
            sb.Append('.');
            sb.Append(methodName);
            sb.Append(methodTypeArguments);
            sb.Append('(');
            sb.Append(arguments);
            sb.AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("CascadingComputeInterceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool IsSupportedMethod(IMethodSymbol method)
    {
        if (method.MethodKind != MethodKind.Ordinary)
            return false;

        if (method.ReturnsVoid)
            return false;

        if (method.IsStatic || method.IsGenericMethod)
            return false;

        return method.Parameters.All(parameter => parameter.RefKind == RefKind.None);
    }

    private static bool HasCascadingComputeAttribute(IMethodSymbol methodSymbol)
    {
        if (methodSymbol.GetAttributes().Any(attribute => IsCascadingComputeAttribute(attribute.AttributeClass)))
            return true;

        if (methodSymbol.OriginalDefinition.GetAttributes().Any(attribute => IsCascadingComputeAttribute(attribute.AttributeClass)))
            return true;

        if (methodSymbol.OverriddenMethod is not null && HasCascadingComputeAttribute(methodSymbol.OverriddenMethod))
            return true;

        foreach (var interfaceMethod in methodSymbol.ExplicitInterfaceImplementations)
        {
            if (HasCascadingComputeAttribute(interfaceMethod))
                return true;
        }

        return false;
    }

    private static bool IsCascadingComputeAttribute(INamedTypeSymbol? attributeType)
        => attributeType?.ToDisplayString() == AttributeMetadataName;

    private static string GetParameterList(IMethodSymbol method)
    {
        if (method.Parameters.Length == 0)
            return string.Empty;

        return string.Join(", ", method.Parameters.Select(parameter =>
        {
            var modifier = parameter.IsParams ? "params " : string.Empty;
            var typeName = parameter.Type.ToDisplayString(NullableFullyQualifiedFormat);
            var defaultValue = parameter.HasExplicitDefaultValue ? " = " + GetDefaultValueExpression(parameter) : string.Empty;
            return $"{modifier}{typeName} {EscapeIdentifier(parameter.Name)}{defaultValue}";
        }));
    }

    private static string GetMethodTypeParameters(IMethodSymbol method)
    {
        if (method.TypeParameters.Length == 0)
            return string.Empty;

        return $"<{string.Join(", ", method.TypeParameters.Select(parameter => parameter.Name))}>";
    }

    private static string GetMethodTypeArguments(IMethodSymbol method)
    {
        if (method.TypeParameters.Length == 0)
            return string.Empty;

        return $"<{string.Join(", ", method.TypeParameters.Select(parameter => parameter.Name))}>";
    }

    private static IReadOnlyList<string> GetMethodConstraints(IMethodSymbol method)
    {
        if (method.TypeParameters.Length == 0)
            return Array.Empty<string>();

        return GetTypeParameterConstraints(method.TypeParameters);
    }

    private static string GetInterceptorTypeParameters(IMethodSymbol method)
    {
        var typeParameters = GetInterceptorTypeParameterSymbols(method);
        if (typeParameters.Count == 0)
            return string.Empty;

        return $"<{string.Join(", ", typeParameters.Select(parameter => parameter.Name))}>";
    }

    private static IReadOnlyList<string> GetInterceptorTypeConstraints(IMethodSymbol method)
    {
        var typeParameters = GetInterceptorTypeParameterSymbols(method);
        if (typeParameters.Count == 0)
            return Array.Empty<string>();

        return GetTypeParameterConstraints(typeParameters);
    }

    private static List<ITypeParameterSymbol> GetInterceptorTypeParameterSymbols(IMethodSymbol method)
    {
        var typeParameters = new List<ITypeParameterSymbol>();
        AddTypeParameters(method.ContainingType, typeParameters);
        foreach (var typeParameter in method.TypeParameters)
            AddTypeParameter(typeParameter, typeParameters);
        return typeParameters;
    }

    private static IReadOnlyList<string> GetTypeParameterConstraints(IEnumerable<ITypeParameterSymbol> typeParameters)
    {

        var constraints = new List<string>();
        foreach (var typeParameter in typeParameters)
        {
            var parts = new List<string>();
            if (typeParameter.HasNotNullConstraint)
                parts.Add("notnull");
            if (typeParameter.HasReferenceTypeConstraint)
                parts.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            if (typeParameter.HasUnmanagedTypeConstraint)
                parts.Add("unmanaged");
            if (typeParameter.HasValueTypeConstraint)
                parts.Add("struct");

            parts.AddRange(typeParameter.ConstraintTypes.Select(constraintType => constraintType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            if (typeParameter.HasConstructorConstraint)
                parts.Add("new()");

            if (parts.Count == 0)
                continue;

            constraints.Add($"where {typeParameter.Name} : {string.Join(", ", parts)}");
        }

        return constraints;
    }

    private static void AddTypeParameters(ITypeSymbol typeSymbol, List<ITypeParameterSymbol> typeParameters)
    {
        switch (typeSymbol)
        {
            case ITypeParameterSymbol typeParameter:
                AddTypeParameter(typeParameter, typeParameters);
                return;
            case IArrayTypeSymbol arrayType:
                AddTypeParameters(arrayType.ElementType, typeParameters);
                return;
            case INamedTypeSymbol namedType:
                foreach (var typeArgument in namedType.TypeArguments)
                    AddTypeParameters(typeArgument, typeParameters);
                return;
        }
    }

    private static void AddTypeParameter(ITypeParameterSymbol typeParameter, List<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.Any(existing => SymbolEqualityComparer.Default.Equals(existing, typeParameter)))
            return;

        typeParameters.Add(typeParameter);
    }

    private static string EscapeIdentifier(string name)
        => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    private static string GetDefaultValueExpression(IParameterSymbol parameter)
    {
        if (!parameter.HasExplicitDefaultValue)
            return string.Empty;

        if (parameter.ExplicitDefaultValue is null)
            return parameter.Type.IsValueType
                ? $"default({parameter.Type.ToDisplayString(NullableFullyQualifiedFormat)})"
                : "null";

        if (parameter.Type.TypeKind == TypeKind.Enum && parameter.Type is INamedTypeSymbol enumType)
        {
            var enumMember = enumType.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(member => member.HasConstantValue && Equals(member.ConstantValue, parameter.ExplicitDefaultValue));

            if (enumMember is not null)
                return $"{enumType.ToDisplayString(NullableFullyQualifiedFormat)}.{enumMember.Name}";

            return $"({enumType.ToDisplayString(NullableFullyQualifiedFormat)}){SymbolDisplay.FormatPrimitive(parameter.ExplicitDefaultValue, quoteStrings: true, useHexadecimalNumbers: false)}";
        }

        return SymbolDisplay.FormatPrimitive(parameter.ExplicitDefaultValue, quoteStrings: true, useHexadecimalNumbers: false)
            ?? throw new InvalidOperationException($"Unable to format default value of parameter {parameter}");
    }

    private static string GetInterceptorName(string methodName, int index)
    {
        var safeName = new string(methodName.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray());
        return $"Intercept_{safeName}_{index}";
    }

    private static string NormalizeCommentText(string value)
        => value.Replace("\r", " ").Replace("\n", " ");

    private static bool IsGeneratedFile(string filePath)
        => filePath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
           || filePath.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)
           || filePath.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase)
           || filePath.Contains("/obj/", StringComparison.OrdinalIgnoreCase);

    private static Location? GetMethodNameLocation(InvocationExpressionSyntax invocation)
    {
        return invocation.Expression switch
        {
            MemberAccessExpressionSyntax memberAccess => memberAccess.Name.GetLocation(),
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name.GetLocation(),
            IdentifierNameSyntax identifier => identifier.GetLocation(),
            GenericNameSyntax genericName => genericName.GetLocation(),
            _ => null
        };
    }

    private sealed class InvocationCandidate
    {
        public InvocationCandidate(IMethodSymbol method, InterceptableLocation location, string sourcePath, int sourceLineNumber)
        {
            Method = method;
            Location = location;
            SourcePath = sourcePath;
            SourceLineNumber = sourceLineNumber;
        }

        public IMethodSymbol Method { get; }

        public InterceptableLocation Location { get; }

        public string SourcePath { get; }

        public int SourceLineNumber { get; }
    }
}
