using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;

namespace hhnl.CascadingCompute.AspNetCore.Client.Generators.Generators;

[Generator]
public sealed class CascadingComputeClientGenerator : IIncrementalGenerator
{
    private const string ServiceClientNamespace = "hhnl.CascadingCompute.AspNetCore.Client";
    private const string ServiceClientName = "CascadingComputeServiceClient";
    private const string RouteGetAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeGetAttribute";
    private const string RoutePostAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputePostAttribute";
    private const string RoutePutAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputePutAttribute";
    private const string RouteDeleteAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeDeleteAttribute";
    private const string RouteHeadAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeHeadAttribute";
    private const string RoutePatchAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputePatchAttribute";
    private const string RouteOptionsAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeOptionsAttribute";
    private const string InterfaceRouteAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeRouteAttribute";
    private const string RouteFromBodyAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeRouteFromBodyAttribute";
    private const string CancellationTokenMetadataName = "System.Threading.CancellationToken";

    private static readonly SymbolDisplayFormat NullableFullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly IEqualityComparer<INamedTypeSymbol> NamedTypeSymbolComparer = new NamedTypeSymbolEqualityComparer();

    private static readonly DiagnosticDescriptor ClassMustBePartial = new(
        "CCACG001",
        "Cascading compute service client must be partial",
        "Class '{0}' must be declared partial to generate CascadingCompute ASP.NET Core client members",
        "CascadingCompute",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serviceClients = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!)
            .Where(static symbol => IsServiceClient(symbol));

        context.RegisterSourceOutput(serviceClients.Collect(), static (spc, classes) => Execute(spc, classes));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> classes)
    {
        foreach (var classSymbol in classes.Distinct(NamedTypeSymbolComparer))
        {
            if (!IsPartial(classSymbol, out var nonPartialLocation))
            {
                context.ReportDiagnostic(Diagnostic.Create(ClassMustBePartial, nonPartialLocation, classSymbol.ToDisplayString()));
                continue;
            }

            var serviceInterface = GetServiceInterfaceType(classSymbol);
            if (serviceInterface is null)
                continue;

            var source = GenerateClientSource(classSymbol, serviceInterface);
            context.AddSource(GetHintName(classSymbol), SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateClientSource(INamedTypeSymbol clientClass, INamedTypeSymbol serviceInterface)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (!clientClass.ContainingNamespace.IsGlobalNamespace)
        {
            sb.Append("namespace ");
            sb.AppendLine(clientClass.ContainingNamespace.ToDisplayString());
            sb.AppendLine("{");
        }

        var indent = string.Empty;
        var serviceInterfaceTypeName = serviceInterface.ToDisplayString(NullableFullyQualifiedFormat);
        var baseRoute = GetControllerRouteTemplate(serviceInterface) ?? string.Empty;

        foreach (var containingType in GetContainingTypes(clientClass))
        {
            sb.Append(indent);
            sb.Append(GetAccessibility(containingType.DeclaredAccessibility));
            sb.Append(" partial ");
            sb.Append(GetTypeKeyword(containingType));
            sb.Append(' ');
            sb.Append(containingType.Name);
            sb.Append(GetTypeParameters(containingType));

            if (SymbolEqualityComparer.Default.Equals(containingType, clientClass)
                && !ImplementsInterface(clientClass, serviceInterface))
            {
                sb.Append(" : ");
                sb.Append(serviceInterfaceTypeName);
            }

            sb.AppendLine();
            var constraints = GetTypeConstraints(containingType);
            foreach (var constraint in constraints)
            {
                sb.Append(indent);
                sb.Append("    ");
                sb.AppendLine(constraint);
            }

            sb.Append(indent);
            sb.AppendLine("{");
            indent += "    ";
        }

        if (!HasBaseRouteProperty(clientClass))
        {
            sb.Append(indent);
            sb.Append("protected override string BaseRoute => \"");
            sb.Append(EscapeStringLiteral(baseRoute));
            sb.AppendLine("\";");
            sb.AppendLine();
        }

        sb.Append(indent);
        sb.AppendLine("private static string __BuildUrl(string baseRoute, string methodRoute, (string Name, object? Value)[] routeValues, (string Name, object? Value)[] queryValues)");
        sb.Append(indent);
        sb.AppendLine("{");
        sb.Append(indent);
        sb.AppendLine("    var normalizedBaseRoute = string.IsNullOrWhiteSpace(baseRoute) ? string.Empty : baseRoute.Trim('/');");
        sb.Append(indent);
        sb.AppendLine("    var normalizedMethodRoute = string.IsNullOrWhiteSpace(methodRoute) ? string.Empty : methodRoute.Trim('/');");
        sb.Append(indent);
        sb.AppendLine("    var fullPath = string.IsNullOrEmpty(normalizedBaseRoute) ? normalizedMethodRoute : $\"{normalizedBaseRoute}/{normalizedMethodRoute}\";");
        sb.Append(indent);
        sb.AppendLine("    foreach (var routeValue in routeValues)");
        sb.Append(indent);
        sb.AppendLine("    {");
        sb.Append(indent);
        sb.AppendLine("        var escapedValue = global::System.Uri.EscapeDataString(global::System.Convert.ToString(routeValue.Value, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty);");
        sb.Append(indent);
        sb.AppendLine("        var escapedName = global::System.Text.RegularExpressions.Regex.Escape(routeValue.Name);");
        sb.Append(indent);
        sb.AppendLine("        var pattern = \"\\\\{\" + escapedName + \"(?::[^}]+)?\\\\}\";");
        sb.Append(indent);
        sb.AppendLine("        fullPath = global::System.Text.RegularExpressions.Regex.Replace(fullPath, pattern, escapedValue);");
        sb.Append(indent);
        sb.AppendLine("    }");
        sb.Append(indent);
        sb.AppendLine("    if (queryValues.Length == 0)");
        sb.Append(indent);
        sb.AppendLine("        return fullPath;");
        sb.Append(indent);
        sb.AppendLine("    var queryBuilder = new global::System.Text.StringBuilder();");
        sb.Append(indent);
        sb.AppendLine("    for (var index = 0; index < queryValues.Length; index++)");
        sb.Append(indent);
        sb.AppendLine("    {");
        sb.Append(indent);
        sb.AppendLine("        if (index > 0)");
        sb.Append(indent);
        sb.AppendLine("            queryBuilder.Append('&');");
        sb.Append(indent);
        sb.AppendLine("        queryBuilder.Append(global::System.Uri.EscapeDataString(queryValues[index].Name));");
        sb.Append(indent);
        sb.AppendLine("        queryBuilder.Append('=');");
        sb.Append(indent);
        sb.AppendLine("        queryBuilder.Append(global::System.Uri.EscapeDataString(global::System.Convert.ToString(queryValues[index].Value, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));");
        sb.Append(indent);
        sb.AppendLine("    }");
        sb.Append(indent);
        sb.AppendLine("    return fullPath + \"?\" + queryBuilder.ToString();");
        sb.Append(indent);
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var serviceMethod in GetServiceMethods(serviceInterface))
        {
            var existingMethod = FindClientMethod(clientClass, serviceMethod);
            if (existingMethod is not null && !existingMethod.IsPartialDefinition)
                continue;

            AppendServiceMethod(sb, indent, serviceMethod, existingMethod);
        }

        for (var i = 0; i < GetContainingTypeCount(clientClass); i++)
        {
            indent = indent.Length >= 4 ? indent.Substring(0, indent.Length - 4) : string.Empty;
            sb.Append(indent);
            sb.AppendLine("}");
        }

        if (!clientClass.ContainingNamespace.IsGlobalNamespace)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendServiceMethod(StringBuilder sb, string indent, IMethodSymbol serviceMethod, IMethodSymbol? existingMethod)
    {
        var methodRoute = GetRouteTemplate(serviceMethod);
        var methodName = serviceMethod.Name;
        var methodParameters = serviceMethod.Parameters;

        var routeParameterNames = GetRouteParameterNames(methodRoute);
        var bodyParameter = methodParameters.FirstOrDefault(HasRouteFromBodyAttribute);
        var cancellationParameter = methodParameters.FirstOrDefault(IsCancellationTokenParameter);

        var routeParameters = methodParameters
            .Where(parameter => !IsCancellationTokenParameter(parameter)
                && !HasRouteFromBodyAttribute(parameter)
                && routeParameterNames.Contains(parameter.Name))
            .ToList();

        var queryParameters = methodParameters
            .Where(parameter => !IsCancellationTokenParameter(parameter)
                && !HasRouteFromBodyAttribute(parameter)
                && !routeParameterNames.Contains(parameter.Name))
            .ToList();

        var cancellationTokenExpression = cancellationParameter is null
            ? "global::System.Threading.CancellationToken.None"
            : EscapeIdentifier(cancellationParameter.Name);

        var returnTypeName = serviceMethod.ReturnType.ToDisplayString(NullableFullyQualifiedFormat);
        var parameterList = GetMethodParameterList(serviceMethod);
        var httpMethodExpression = GetHttpMethodExpression(serviceMethod);
        var isTaskReturn = IsTask(serviceMethod.ReturnType, out var taskTypeArgument);
        var hasReturnValue = !serviceMethod.ReturnsVoid && !(isTaskReturn && taskTypeArgument is null);
        var methodAccessibility = existingMethod is null ? "public" : GetAccessibility(existingMethod.DeclaredAccessibility);
        var partialModifier = existingMethod?.IsPartialDefinition == true ? " partial" : string.Empty;

        sb.Append(indent);
        sb.Append(methodAccessibility);
        sb.Append(partialModifier);
        sb.Append(' ');
        if (isTaskReturn)
            sb.Append("async ");
        sb.Append(returnTypeName);
        sb.Append(' ');
        sb.Append(methodName);
        sb.Append('(');
        sb.Append(parameterList);
        sb.AppendLine(")");
        sb.Append(indent);
        sb.AppendLine("{");

        sb.Append(indent);
        sb.Append("    var __url = __BuildUrl(BaseRoute, \"");
        sb.Append(EscapeStringLiteral(methodRoute));
        sb.Append("\", ");
        sb.Append(GetTupleArrayExpression(routeParameters));
        sb.Append(", ");
        sb.Append(GetTupleArrayExpression(queryParameters));
        sb.AppendLine(");");

        sb.Append(indent);
        sb.Append("    using var __request = new global::System.Net.Http.HttpRequestMessage(");
        sb.Append(httpMethodExpression);
        sb.AppendLine(", __url);");

        if (bodyParameter is not null)
        {
            sb.Append(indent);
            sb.Append("    __request.Content = global::System.Net.Http.Json.JsonContent.Create(");
            sb.Append(EscapeIdentifier(bodyParameter.Name));
            sb.AppendLine(");");
        }

        if (isTaskReturn)
        {
            sb.Append(indent);
            sb.Append("    using var __response = await _httpClient.SendAsync(__request, ");
            sb.Append(cancellationTokenExpression);
            sb.AppendLine(").ConfigureAwait(false);");
            sb.Append(indent);
            sb.AppendLine("    __response.EnsureSuccessStatusCode();");

            if (taskTypeArgument is null)
            {
                sb.Append(indent);
                sb.AppendLine("    return;");
            }
            else
            {
                if (hasReturnValue)
                {
                    sb.Append(indent);
                    sb.AppendLine("    CaptureCacheContext(__url);");
                }

                sb.Append(indent);
                sb.Append("    return (await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<");
                sb.Append(taskTypeArgument.ToDisplayString(NullableFullyQualifiedFormat));
                sb.Append(">(__response.Content, cancellationToken: ");
                sb.Append(cancellationTokenExpression);
                sb.AppendLine(").ConfigureAwait(false))!;");
            }
        }
        else
        {
            sb.Append(indent);
            sb.Append("    using var __response = _httpClient.SendAsync(__request, ");
            sb.Append(cancellationTokenExpression);
            sb.AppendLine(").GetAwaiter().GetResult();");
            sb.Append(indent);
            sb.AppendLine("    __response.EnsureSuccessStatusCode();");

            if (hasReturnValue)
            {
                sb.Append(indent);
                sb.AppendLine("    CaptureCacheContext(__url);");
            }

            sb.Append(indent);
            sb.Append("    return global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<");
            sb.Append(serviceMethod.ReturnType.ToDisplayString(NullableFullyQualifiedFormat));
            sb.Append(">(__response.Content, cancellationToken: ");
            sb.Append(cancellationTokenExpression);
            sb.AppendLine(").GetAwaiter().GetResult()!;");
        }

        sb.Append(indent);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string GetTupleArrayExpression(IReadOnlyList<IParameterSymbol> parameters)
    {
        if (parameters.Count == 0)
            return "global::System.Array.Empty<(string Name, object? Value)>()";

        var entries = parameters.Select(parameter => $"(\"{EscapeStringLiteral(parameter.Name)}\", (object?){EscapeIdentifier(parameter.Name)})");
        return $"new (string Name, object? Value)[] {{ {string.Join(", ", entries)} }}";
    }

    private static HashSet<string> GetRouteParameterNames(string routeTemplate)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        foreach (Match match in Regex.Matches(routeTemplate, "\\{(?<name>[^}:]+)(?::[^}]+)?\\}"))
        {
            if (match.Groups["name"].Success)
                result.Add(match.Groups["name"].Value);
        }

        return result;
    }

    private static bool IsCancellationTokenParameter(IParameterSymbol parameter)
        => parameter.Type.ToDisplayString(NullableFullyQualifiedFormat).Replace("global::", string.Empty) == CancellationTokenMetadataName;

    private static bool HasRouteFromBodyAttribute(IParameterSymbol parameter)
        => parameter.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == RouteFromBodyAttributeMetadataName);

    private static string GetHttpMethodExpression(IMethodSymbol method)
    {
        var routeAttribute = GetRouteAttribute(method);
        var routeName = routeAttribute?.AttributeClass?.ToDisplayString();
        return routeName switch
        {
            RoutePostAttributeMetadataName => "global::System.Net.Http.HttpMethod.Post",
            RoutePutAttributeMetadataName => "global::System.Net.Http.HttpMethod.Put",
            RouteDeleteAttributeMetadataName => "global::System.Net.Http.HttpMethod.Delete",
            RouteHeadAttributeMetadataName => "global::System.Net.Http.HttpMethod.Head",
            RoutePatchAttributeMetadataName => "global::System.Net.Http.HttpMethod.Patch",
            RouteOptionsAttributeMetadataName => "global::System.Net.Http.HttpMethod.Options",
            _ => "global::System.Net.Http.HttpMethod.Get"
        };
    }

    private static string GetMethodParameterList(IMethodSymbol method)
        => string.Join(", ", method.Parameters.Select(parameter =>
        {
            var modifier = parameter.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => string.Empty
            };
            var paramsModifier = parameter.IsParams ? "params " : string.Empty;
            return $"{modifier}{paramsModifier}{parameter.Type.ToDisplayString(NullableFullyQualifiedFormat)} {EscapeIdentifier(parameter.Name)}";
        }));

    private static string GetRouteTemplate(IMethodSymbol serviceMethod)
    {
        var routeAttribute = GetRouteAttribute(serviceMethod);
        if (routeAttribute?.ConstructorArguments is { Length: > 0 }
            && routeAttribute.ConstructorArguments[0] is { Kind: TypedConstantKind.Primitive, Value: string template }
            && !string.IsNullOrWhiteSpace(template))
            return template;

        return serviceMethod.Name;
    }

    private static AttributeData? GetRouteAttribute(IMethodSymbol serviceMethod)
    {
        foreach (var attribute in serviceMethod.GetAttributes())
        {
            var attributeName = attribute.AttributeClass?.ToDisplayString();
            if (attributeName == RouteGetAttributeMetadataName
                || attributeName == RoutePostAttributeMetadataName
                || attributeName == RoutePutAttributeMetadataName
                || attributeName == RouteDeleteAttributeMetadataName
                || attributeName == RouteHeadAttributeMetadataName
                || attributeName == RoutePatchAttributeMetadataName
                || attributeName == RouteOptionsAttributeMetadataName)
                return attribute;
        }

        return null;
    }

    private static string? GetControllerRouteTemplate(INamedTypeSymbol serviceInterface)
    {
        var routeAttribute = serviceInterface.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == InterfaceRouteAttributeMetadataName);

        if (routeAttribute?.ConstructorArguments is { Length: > 0 }
            && routeAttribute.ConstructorArguments[0] is { Kind: TypedConstantKind.Primitive, Value: string template }
            && !string.IsNullOrWhiteSpace(template))
            return template;

        return null;
    }

    private static bool IsTask(ITypeSymbol typeSymbol, out ITypeSymbol? taskTypeArgument)
    {
        taskTypeArgument = null;
        if (typeSymbol is not INamedTypeSymbol named)
            return false;

        if (named.Name != "Task" || named.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
            return false;

        if (named.TypeArguments.Length == 1)
            taskTypeArgument = named.TypeArguments[0];

        return true;
    }

    private static IEnumerable<IMethodSymbol> GetServiceMethods(INamedTypeSymbol serviceInterface)
    {
        var methods = serviceInterface
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static method => method.MethodKind == MethodKind.Ordinary && !method.IsStatic)
            .ToList();

        foreach (var baseInterface in serviceInterface.AllInterfaces)
        {
            methods.AddRange(baseInterface
                .GetMembers()
                .OfType<IMethodSymbol>()
                .Where(static method => method.MethodKind == MethodKind.Ordinary && !method.IsStatic));
        }

        return methods
            .GroupBy(GetMethodSignatureKey, StringComparer.Ordinal)
            .Select(group => group.First());
    }

    private static string GetMethodSignatureKey(IMethodSymbol method)
        => $"{method.Name}|{method.Arity}|{method.ReturnType.ToDisplayString(NullableFullyQualifiedFormat)}|{string.Join(",", method.Parameters.Select(parameter => $"{parameter.RefKind}:{parameter.Type.ToDisplayString(NullableFullyQualifiedFormat)}"))}";

    private static IMethodSymbol? FindClientMethod(INamedTypeSymbol clientClass, IMethodSymbol serviceMethod)
    {
        foreach (var candidate in clientClass.GetMembers(serviceMethod.Name).OfType<IMethodSymbol>())
        {
            if (candidate.MethodKind != MethodKind.Ordinary)
                continue;

            if (!SymbolEqualityComparer.Default.Equals(candidate.ReturnType, serviceMethod.ReturnType))
                continue;

            if (candidate.Parameters.Length != serviceMethod.Parameters.Length)
                continue;

            var allParametersMatch = true;
            for (var index = 0; index < candidate.Parameters.Length; index++)
            {
                var left = candidate.Parameters[index];
                var right = serviceMethod.Parameters[index];
                if (left.RefKind != right.RefKind || !SymbolEqualityComparer.Default.Equals(left.Type, right.Type))
                {
                    allParametersMatch = false;
                    break;
                }
            }

            if (allParametersMatch)
                return candidate;
        }

        return null;
    }

    private static bool HasBaseRouteProperty(INamedTypeSymbol clientClass)
        => clientClass.GetMembers("BaseRoute")
            .OfType<IPropertySymbol>()
            .Any(property => property is { IsStatic: false, Parameters.Length: 0 });

    private static bool ImplementsInterface(INamedTypeSymbol clientClass, INamedTypeSymbol interfaceSymbol)
        => clientClass.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol) || SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, interfaceSymbol.OriginalDefinition));

    private static bool IsServiceClient(INamedTypeSymbol typeSymbol)
        => GetServiceInterfaceType(typeSymbol) is not null;

    private static INamedTypeSymbol? GetServiceInterfaceType(INamedTypeSymbol clientClass)
    {
        var current = clientClass;
        while (current is not null)
        {
            if (current.BaseType is INamedTypeSymbol baseType
                && baseType.OriginalDefinition is { Name: ServiceClientName, Arity: 1 }
                && baseType.OriginalDefinition.ContainingNamespace.ToDisplayString() == ServiceClientNamespace
                && baseType.TypeArguments.Length == 1
                && baseType.TypeArguments[0] is INamedTypeSymbol serviceType
                && serviceType.TypeKind == TypeKind.Interface)
                return serviceType;

            current = current.BaseType;
        }

        return null;
    }

    private static bool IsPartial(INamedTypeSymbol typeSymbol, out Location? nonPartialLocation)
    {
        foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax() is TypeDeclarationSyntax typeDeclaration
                && !typeDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                nonPartialLocation = typeDeclaration.Identifier.GetLocation();
                return false;
            }
        }

        nonPartialLocation = typeSymbol.Locations.FirstOrDefault();
        return true;
    }

    private static string GetHintName(INamedTypeSymbol typeSymbol)
    {
        var name = typeSymbol.ToDisplayString(NullableFullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace('.', '_');
        return $"{name}.CascadingComputeClient.g.cs";
    }

    private static IEnumerable<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol typeSymbol)
    {
        var stack = new Stack<INamedTypeSymbol>();
        var current = typeSymbol;
        while (current is not null)
        {
            stack.Push(current);
            current = current.ContainingType;
        }

        return stack;
    }

    private static int GetContainingTypeCount(INamedTypeSymbol typeSymbol)
    {
        var count = 0;
        var current = typeSymbol;
        while (current is not null)
        {
            count++;
            current = current.ContainingType;
        }

        return count;
    }

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };

    private static string GetTypeKeyword(INamedTypeSymbol typeSymbol)
        => typeSymbol.TypeKind == TypeKind.Interface ? "interface" : typeSymbol.IsRecord ? "record" : "class";

    private static string GetTypeParameters(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
            return string.Empty;

        return $"<{string.Join(", ", typeSymbol.TypeParameters.Select(parameter => parameter.Name))}>";
    }

    private static IReadOnlyList<string> GetTypeConstraints(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
            return [];

        var constraints = new List<string>();
        foreach (var typeParameter in typeSymbol.TypeParameters)
        {
            var parts = new List<string>();
            if (typeParameter.HasNotNullConstraint)
                parts.Add("notnull");
            if (typeParameter.HasReferenceTypeConstraint)
                parts.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            if (typeParameter.HasUnmanagedTypeConstraint)
                parts.Add("unmanaged");
            if (typeParameter.HasValueTypeConstraint)
                parts.Add("struct");

            parts.AddRange(typeParameter.ConstraintTypes.Select(constraintType => constraintType.ToDisplayString(NullableFullyQualifiedFormat)));

            if (typeParameter.HasConstructorConstraint)
                parts.Add("new()");

            if (parts.Count == 0)
                continue;

            constraints.Add($"where {typeParameter.Name} : {string.Join(", ", parts)}");
        }

        return constraints;
    }

    private static string EscapeIdentifier(string name)
        => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    private static string EscapeStringLiteral(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");

    private sealed class NamedTypeSymbolEqualityComparer : IEqualityComparer<INamedTypeSymbol>
    {
        public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y)
            => SymbolEqualityComparer.Default.Equals(x, y);

        public int GetHashCode(INamedTypeSymbol obj)
            => SymbolEqualityComparer.Default.GetHashCode(obj);
    }
}
