using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace hhnl.CascadingCompute.AspNetCore.Generators.Generators;

[Generator]
public sealed class CascadingComputeControllerGenerator : IIncrementalGenerator
{
    private const string ControllerAttributeMetadataName = "hhnl.CascadingCompute.AspNetCore.Shared.Attributes.CascadingComputeControllerAttribute";
    private const string ControllerInterfaceMetadataName = "hhnl.CascadingCompute.AspNetCore.Interfaces.ICascadingComputeController";
    private const string TypeFilterAttributeMetadataName = "Microsoft.AspNetCore.Mvc.TypeFilterAttribute";
    private const string CacheContextProviderInterfaceNamespace = "hhnl.CascadingCompute.Shared.Interfaces";
    private const string CacheContextProviderInterfaceName = "ICacheContextProvider";

    private static readonly SymbolDisplayFormat NullableFullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly IEqualityComparer<INamedTypeSymbol> NamedTypeSymbolComparer = new NamedTypeSymbolEqualityComparer();

    private static readonly DiagnosticDescriptor ClassMustBePartial = new(
        "CCAG001",
        "Cascading compute ASP.NET Core controller must be partial",
        "Class '{0}' must be declared partial to generate CascadingCompute ASP.NET Core controller members",
        "CascadingCompute",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var controllers = context.SyntaxProvider.ForAttributeWithMetadataName(
            ControllerAttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(controllers.Collect(), static (spc, classes) => Execute(spc, classes));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> classes)
    {
        foreach (var classSymbol in classes.Distinct(NamedTypeSymbolComparer))
        {
            if (classSymbol is null)
                continue;

            if (!IsPartial(classSymbol, out var nonPartialLocation))
            {
                context.ReportDiagnostic(Diagnostic.Create(ClassMustBePartial, nonPartialLocation, classSymbol.ToDisplayString()));
                continue;
            }

            var source = GenerateControllerSource(classSymbol);
            context.AddSource(GetHintName(classSymbol), SourceText.From(source, Encoding.UTF8));
        }
    }

    private static bool IsPartial(INamedTypeSymbol typeSymbol, out Location? nonPartialLocation)
    {
        foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax() is TypeDeclarationSyntax typeDeclaration
                && !typeDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                nonPartialLocation = typeDeclaration.Identifier.GetLocation();
                return false;
            }
        }

        nonPartialLocation = typeSymbol.Locations.FirstOrDefault();
        return true;
    }

    private static string GenerateControllerSource(INamedTypeSymbol controller)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        if (!controller.ContainingNamespace.IsGlobalNamespace)
        {
            sb.Append("namespace ");
            sb.AppendLine(controller.ContainingNamespace.ToDisplayString());
            sb.AppendLine("{");
        }

        var indent = string.Empty;
        foreach (var containingType in GetContainingTypes(controller))
        {
            if (SymbolEqualityComparer.Default.Equals(containingType, controller)
                && !HasTypeFilterAttribute(controller))
            {
                sb.Append(indent);
                sb.Append("[global::Microsoft.AspNetCore.Mvc.TypeFilterAttribute(typeof(global::hhnl.CascadingCompute.AspNetCore.CascadingComputeActionFilter<");
                sb.Append(GetContainingTypeName(controller));
                sb.AppendLine(">))]");
            }

            sb.Append(indent);
            sb.Append(GetAccessibility(containingType.DeclaredAccessibility));
            sb.Append(" partial ");
            sb.Append(GetTypeKeyword(containingType));
            sb.Append(' ');
            sb.Append(containingType.Name);
            sb.Append(GetTypeParameters(containingType));

            if (SymbolEqualityComparer.Default.Equals(containingType, controller)
                && !ImplementsControllerInterface(controller))
            {
                sb.Append(" : global::");
                sb.Append(ControllerInterfaceMetadataName);
            }

            sb.AppendLine();

            var constraints = GetTypeConstraints(containingType);
            foreach (var constraint in constraints)
            {
                sb.Append(indent);
                sb.Append("    ");
                sb.AppendLine(constraint);
            }

            sb.Append(indent);
            sb.AppendLine("{");
            indent += "    ";
        }

        var primaryConstructorCacheContexts = GetPrimaryConstructorCacheContextParameters(controller);
        foreach (var cacheContextParameter in primaryConstructorCacheContexts)
        {
            sb.Append(indent);
            sb.Append("private ");
            sb.Append(cacheContextParameter.ContextTypeName);
            sb.Append(' ');
            sb.Append(cacheContextParameter.HelperMethodName);
            sb.Append("() => ");
            sb.Append(EscapeIdentifier(cacheContextParameter.ParameterName));
            sb.AppendLine(".GetCacheContext();");
            sb.AppendLine();
        }

        if (!HasGetCacheContextMethod(controller))
        {
            sb.Append(indent);
            sb.AppendLine("public global::System.Collections.Generic.IReadOnlyCollection<(string Key, object Value)> GetCacheContext()");
            sb.Append(indent);
            sb.Append("    => ");
            sb.Append(GetCacheContextReturnExpression(controller));
            sb.AppendLine(";");
            sb.AppendLine();
        }

        if (!HasInvalidationsAsyncMethod(controller))
        {
            sb.Append(indent);
            sb.AppendLine("[global::Microsoft.AspNetCore.Mvc.HttpGetAttribute(\"invalidations\")]");
            sb.Append(indent);
            sb.Append("public global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Http.HttpResults.ServerSentEventsResult<global::hhnl.CascadingCompute.AspNetCore.Shared.Models.InvalidationDto>> InvalidationsAsync(global::System.Threading.CancellationToken cancellationToken)");
            sb.AppendLine();
            sb.Append(indent);
            sb.AppendLine("{");
            sb.Append(indent);
            sb.Append("    return global::System.Threading.Tasks.Task.FromResult(global::Microsoft.AspNetCore.Http.TypedResults.ServerSentEvents(global::hhnl.CascadingCompute.AspNetCore.Utils.Utils.StreamInvalidationEvents<");
            sb.Append(GetContainingTypeName(controller));
            sb.AppendLine(">(GetCacheContext(), cancellationToken), \"invalidations\"));");
            sb.Append(indent);
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (!HasOnCacheEntryInvalidatedMethod(controller))
        {
            sb.Append(indent);
            sb.AppendLine("public static void OnCacheEntryInvalidated(string url, global::System.Collections.Generic.IReadOnlyCollection<(string Key, object Value)> taints)");
            sb.Append(indent);
            sb.AppendLine("    => CacheEntryInvalidated?.Invoke(null, (url, taints));");
            sb.AppendLine();
        }

        if (!HasCacheEntryInvalidatedEvent(controller))
        {
            sb.Append(indent);
            sb.AppendLine("public static event global::System.EventHandler<(string url, global::System.Collections.Generic.IReadOnlyCollection<(string Key, object Value)> taints)>? CacheEntryInvalidated;");
            sb.AppendLine();
        }

        for (var i = 0; i < GetContainingTypeCount(controller); i++)
        {
            indent = indent.Length >= 4 ? indent.Substring(0, indent.Length - 4) : string.Empty;
            sb.Append(indent);
            sb.AppendLine("}");
        }

        if (!controller.ContainingNamespace.IsGlobalNamespace)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool ImplementsControllerInterface(INamedTypeSymbol controller)
        => controller.AllInterfaces.Any(i => i.ToDisplayString() == ControllerInterfaceMetadataName);

    private static bool HasTypeFilterAttribute(INamedTypeSymbol controller)
        => controller.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == TypeFilterAttributeMetadataName);

    private static bool HasGetCacheContextMethod(INamedTypeSymbol controller)
        => controller.GetMembers("GetCacheContext")
            .OfType<IMethodSymbol>()
            .Any(method => !method.IsStatic && method.Parameters.Length == 0);

    private static bool HasInvalidationsAsyncMethod(INamedTypeSymbol controller)
        => controller.GetMembers("InvalidationsAsync")
            .OfType<IMethodSymbol>()
            .Any(method => !method.IsStatic);

    private static bool HasOnCacheEntryInvalidatedMethod(INamedTypeSymbol controller)
        => controller.GetMembers("OnCacheEntryInvalidated")
            .OfType<IMethodSymbol>()
            .Any(method => method.IsStatic && method.Parameters.Length == 2);

    private static bool HasCacheEntryInvalidatedEvent(INamedTypeSymbol controller)
        => controller.GetMembers("CacheEntryInvalidated")
            .OfType<IEventSymbol>()
            .Any(@event => @event.IsStatic);

    private static string GetCacheContextReturnExpression(INamedTypeSymbol controller)
    {
        var taints = GetCacheContextTaints(controller).ToList();
        if (taints.Count == 0)
            return "global::System.Array.Empty<(string Key, object Value)>()";

        var entries = taints.Select(taint => $"(\"{EscapeStringLiteral(taint.Key)}\", (object){taint.ValueExpression}!)");
        return $"new (string Key, object Value)[] {{ {string.Join(", ", entries)} }}";
    }

    private static IEnumerable<CacheContextTaint> GetCacheContextTaints(INamedTypeSymbol controller)
    {
        foreach (var member in controller.GetMembers())
        {
            if (member is IFieldSymbol fieldSymbol
                && !fieldSymbol.IsStatic
                && !fieldSymbol.IsImplicitlyDeclared
                && TryGetCacheContextType(fieldSymbol.Type, out var fieldContextType))
            {
                yield return new CacheContextTaint(
                    GetCacheContextTaintKey(fieldSymbol.Type, fieldContextType),
                    $"{EscapeIdentifier(fieldSymbol.Name)}.GetCacheContext()");
                continue;
            }

            if (member is IPropertySymbol propertySymbol
                && !propertySymbol.IsStatic
                && propertySymbol.GetMethod is not null
                && TryGetCacheContextType(propertySymbol.Type, out var propertyContextType))
            {
                yield return new CacheContextTaint(
                    GetCacheContextTaintKey(propertySymbol.Type, propertyContextType),
                    $"{EscapeIdentifier(propertySymbol.Name)}.GetCacheContext()");
            }
        }

        foreach (var primaryConstructorCacheContext in GetPrimaryConstructorCacheContextParameters(controller))
        {
            yield return new CacheContextTaint(
                GetCacheContextTaintKey(primaryConstructorCacheContext.ProviderTypeName, primaryConstructorCacheContext.ContextTypeName),
                $"{primaryConstructorCacheContext.HelperMethodName}()");
        }
    }

    private static IReadOnlyList<PrimaryConstructorCacheContextParameter> GetPrimaryConstructorCacheContextParameters(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeKind != TypeKind.Class)
            return [];

        var primaryConstructor = typeSymbol.InstanceConstructors
            .FirstOrDefault(ctor => ctor.DeclaringSyntaxReferences
                .Select(reference => reference.GetSyntax())
                .OfType<ClassDeclarationSyntax>()
                .Any(classDeclaration => classDeclaration.ParameterList is not null));

        if (primaryConstructor is null)
            return [];

        var parameters = new List<PrimaryConstructorCacheContextParameter>();
        var index = 0;
        foreach (var parameter in primaryConstructor.Parameters)
        {
            if (!TryGetCacheContextType(parameter.Type, out var cacheContextType))
                continue;

            if (IsPrimaryConstructorParameterAssignedToCacheContextMember(typeSymbol, parameter))
                continue;

            parameters.Add(new PrimaryConstructorCacheContextParameter(
                parameter.Name,
                parameter.Type.ToDisplayString(NullableFullyQualifiedFormat),
                cacheContextType.ToDisplayString(NullableFullyQualifiedFormat),
                $"__GetPrimaryConstructorCacheContext{index++}"));
        }

        return parameters;
    }

    private static bool IsPrimaryConstructorParameterAssignedToCacheContextMember(INamedTypeSymbol typeSymbol, IParameterSymbol parameter)
    {
        foreach (var field in typeSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.IsStatic || field.IsImplicitlyDeclared || !TryGetCacheContextType(field.Type, out _))
                continue;

            foreach (var syntaxReference in field.DeclaringSyntaxReferences)
            {
                if (syntaxReference.GetSyntax() is VariableDeclaratorSyntax { Initializer.Value: IdentifierNameSyntax identifier }
                    && string.Equals(identifier.Identifier.ValueText, parameter.Name, StringComparison.Ordinal))
                    return true;
            }
        }

        foreach (var property in typeSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsImplicitlyDeclared || !TryGetCacheContextType(property.Type, out _))
                continue;

            foreach (var syntaxReference in property.DeclaringSyntaxReferences)
            {
                if (syntaxReference.GetSyntax() is PropertyDeclarationSyntax { Initializer.Value: IdentifierNameSyntax identifier }
                    && string.Equals(identifier.Identifier.ValueText, parameter.Name, StringComparison.Ordinal))
                    return true;
            }
        }

        return false;
    }

    private static bool TryGetCacheContextType(ITypeSymbol typeSymbol, out ITypeSymbol cacheContextType)
    {
        if (typeSymbol is INamedTypeSymbol namedTypeSymbol)
        {
            if (IsCacheContextProviderInterface(namedTypeSymbol))
            {
                cacheContextType = namedTypeSymbol.TypeArguments[0];
                return true;
            }

            foreach (var interfaceSymbol in namedTypeSymbol.AllInterfaces)
            {
                if (IsCacheContextProviderInterface(interfaceSymbol))
                {
                    cacheContextType = interfaceSymbol.TypeArguments[0];
                    return true;
                }
            }
        }

        cacheContextType = null!;
        return false;
    }

    private static bool IsCacheContextProviderInterface(INamedTypeSymbol typeSymbol)
        => typeSymbol is { Name: CacheContextProviderInterfaceName, Arity: 1 }
            && typeSymbol.ContainingNamespace.ToDisplayString() == CacheContextProviderInterfaceNamespace;

    private sealed class CacheContextTaint
    {
        public CacheContextTaint(string key, string valueExpression)
        {
            Key = key;
            ValueExpression = valueExpression;
        }

        public string Key { get; }
        public string ValueExpression { get; }
    }

    private sealed class PrimaryConstructorCacheContextParameter
    {
        public PrimaryConstructorCacheContextParameter(string parameterName, string providerTypeName, string contextTypeName, string helperMethodName)
        {
            ParameterName = parameterName;
            ProviderTypeName = providerTypeName;
            ContextTypeName = contextTypeName;
            HelperMethodName = helperMethodName;
        }

        public string ParameterName { get; }
        public string ProviderTypeName { get; }
        public string ContextTypeName { get; }
        public string HelperMethodName { get; }
    }

    private static string GetCacheContextTaintKey(ITypeSymbol providerType, ITypeSymbol contextType)
        => GetCacheContextTaintKey(
            providerType.ToDisplayString(NullableFullyQualifiedFormat),
            contextType.ToDisplayString(NullableFullyQualifiedFormat));

    private static string GetCacheContextTaintKey(string providerTypeName, string contextTypeName)
        => providerTypeName + "|" + contextTypeName;

    private static string GetHintName(INamedTypeSymbol typeSymbol)
    {
        var name = typeSymbol.ToDisplayString(NullableFullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace('.', '_');
        return $"{name}.CascadingComputeController.g.cs";
    }

    private static IEnumerable<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol typeSymbol)
    {
        var stack = new Stack<INamedTypeSymbol>();
        var current = typeSymbol;
        while (current is not null)
        {
            stack.Push(current);
            current = current.ContainingType;
        }

        return stack;
    }

    private static int GetContainingTypeCount(INamedTypeSymbol typeSymbol)
    {
        var count = 0;
        var current = typeSymbol;
        while (current is not null)
        {
            count++;
            current = current.ContainingType;
        }

        return count;
    }

    private static string GetContainingTypeName(INamedTypeSymbol typeSymbol)
        => typeSymbol.Name + GetTypeParameters(typeSymbol);

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };

    private static string GetTypeKeyword(INamedTypeSymbol typeSymbol)
        => typeSymbol.TypeKind == TypeKind.Interface ? "interface" : typeSymbol.IsRecord ? "record" : "class";

    private static string GetTypeParameters(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
            return string.Empty;

        return $"<{string.Join(", ", typeSymbol.TypeParameters.Select(parameter => parameter.Name))}>";
    }

    private static IReadOnlyList<string> GetTypeConstraints(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
            return [];

        var constraints = new List<string>();
        foreach (var typeParameter in typeSymbol.TypeParameters)
        {
            var parts = new List<string>();
            if (typeParameter.HasNotNullConstraint)
                parts.Add("notnull");
            if (typeParameter.HasReferenceTypeConstraint)
                parts.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            if (typeParameter.HasUnmanagedTypeConstraint)
                parts.Add("unmanaged");
            if (typeParameter.HasValueTypeConstraint)
                parts.Add("struct");

            parts.AddRange(typeParameter.ConstraintTypes.Select(constraintType => constraintType.ToDisplayString(NullableFullyQualifiedFormat)));

            if (typeParameter.HasConstructorConstraint)
                parts.Add("new()");

            if (parts.Count == 0)
                continue;

            constraints.Add($"where {typeParameter.Name} : {string.Join(", ", parts)}");
        }

        return constraints;
    }

    private static string EscapeIdentifier(string name)
        => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    private static string EscapeStringLiteral(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");

    private sealed class NamedTypeSymbolEqualityComparer : IEqualityComparer<INamedTypeSymbol>
    {
        public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y)
            => SymbolEqualityComparer.Default.Equals(x, y);

        public int GetHashCode(INamedTypeSymbol obj)
            => SymbolEqualityComparer.Default.GetHashCode(obj);
    }
}
